# shellcheck shell=sh
# Shared helpers for the event-capture controlled deployment on the production VM.
#
# Sourced by deploy.sh, preflight.sh, backup.sh, health.sh and rollback.sh. This library only
# DEFINES functions and derives paths; it does not `set -e` (the entry scripts do) so it can also
# be sourced by the rollback-guard unit tests. No secrets live here or in any transferred file;
# secrets live only in $SHARED_ENV (/opt/event-capture/shared/production.env, 0600, VM-managed).
#
# On the VM the release bundle is laid out as:
#   $OPT_ROOT/shared/production.env                 secrets (VM-managed, never transferred)
#   $OPT_ROOT/releases/vX.Y.Z/docker-compose.yml    transferred
#   $OPT_ROOT/releases/vX.Y.Z/docker-compose.vm.yml  transferred
#   $OPT_ROOT/releases/vX.Y.Z/release.env            generated by the deploy job (non-secret)
#   $OPT_ROOT/releases/vX.Y.Z/release-manifest.json  audit record
#   $OPT_ROOT/releases/vX.Y.Z/deploy/*.sh            these scripts
#   $OPT_ROOT/current -> releases/vX.Y.Z             last SUCCESSFUL release
#
# Environment overrides (used by the smoke rehearsal to run against a temp root + build images):
#   EVENT_CAPTURE_ROOT              default /opt/event-capture
#   EVENT_CAPTURE_SHARED_ENV       default $OPT_ROOT/shared/production.env
#   EVENT_CAPTURE_COMPOSE_OVERRIDE default docker-compose.vm.yml (smoke uses docker-compose.build.yml)
#   EVENT_CAPTURE_BUILD_IMAGES     default 0 (smoke sets 1 to build instead of pull)
#   EVENT_CAPTURE_HEALTH_TIMEOUT   default 180 (seconds)
#   EVENT_CAPTURE_DISK_MIN_MB      default 2048

OPT_ROOT="${EVENT_CAPTURE_ROOT:-/opt/event-capture}"
SHARED_ENV="${EVENT_CAPTURE_SHARED_ENV:-$OPT_ROOT/shared/production.env}"
COMPOSE_OVERRIDE="${EVENT_CAPTURE_COMPOSE_OVERRIDE:-docker-compose.vm.yml}"
HEALTH_TIMEOUT="${EVENT_CAPTURE_HEALTH_TIMEOUT:-180}"
DISK_MIN_MB="${EVENT_CAPTURE_DISK_MIN_MB:-2048}"
CURRENT_LINK="$OPT_ROOT/current"

log()  { printf '%s [deploy] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }
warn() { printf '%s [deploy] WARN: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >&2; }
die()  { printf '%s [deploy] ERROR: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >&2; exit 1; }

require_cmd() {
  for _c in "$@"; do
    command -v "$_c" >/dev/null 2>&1 || die "required command not found: $_c"
  done
}

# Deploy scripts refuse anything but a strict vMAJOR.MINOR.PATCH tag.
validate_release_tag() {
  printf '%s' "${1:-}" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$' \
    || die "invalid release tag: '${1:-}' (expected vMAJOR.MINOR.PATCH)"
}

release_dir() { printf '%s/releases/%s' "$OPT_ROOT" "$1"; }

# docker compose wrapper bound to a specific release directory.
# Usage: compose <release-dir> <compose args...>
compose() {
  _rd="$1"; shift
  docker compose \
    --env-file "$SHARED_ENV" \
    --env-file "$_rd/release.env" \
    -f "$_rd/docker-compose.yml" \
    -f "$_rd/$COMPOSE_OVERRIDE" \
    "$@"
}

# Read a single KEY=VALUE from a release.env-style file without sourcing it.
env_field() {
  _file="$1"; _key="$2"
  [ -f "$_file" ] || return 1
  awk -F= -v k="$_key" '$1==k { sub(/^[^=]*=/, ""); print; exit }' "$_file"
}

# Source a release.env into the environment (non-secret KEY=VALUE only).
load_release_env() {
  _rd="$1"
  [ -f "$_rd/release.env" ] || die "missing release.env in $_rd"
  set -a
  # shellcheck disable=SC1091
  . "$_rd/release.env"
  set +a
}

service_container() {
  _rd="$1"; _svc="$2"
  compose "$_rd" ps -q "$_svc" 2>/dev/null | head -n1
}

container_state() {
  # 'healthy'/'unhealthy'/'starting' when a healthcheck exists, else running/exited state.
  docker inspect \
    --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' \
    "$1" 2>/dev/null || echo unknown
}

# Wait until a compose service reports a healthy container healthcheck.
# Only call for services that HAVE a healthcheck (postgres, redis, backend-api, backend-worker).
wait_container_healthy() {
  _rd="$1"; _svc="$2"; _timeout="${3:-$HEALTH_TIMEOUT}"
  log "waiting for $_svc to become healthy (timeout ${_timeout}s)"
  _end=$(( $(date +%s) + _timeout ))
  while :; do
    _cid=$(service_container "$_rd" "$_svc" || true)
    if [ -n "$_cid" ]; then
      _st=$(container_state "$_cid")
      case "$_st" in
        healthy) log "$_svc healthy"; return 0 ;;
        unhealthy) warn "$_svc reported unhealthy" ;;
      esac
    fi
    if [ "$(date +%s)" -ge "$_end" ]; then
      warn "$_svc did not become healthy within ${_timeout}s"
      return 1
    fi
    sleep 5
  done
}

# Wait until an actuator readiness endpoint returns HTTP 2xx with status UP.
wait_http_ready() {
  _url="$1"; _timeout="${2:-$HEALTH_TIMEOUT}"
  log "waiting for readiness at $_url (timeout ${_timeout}s)"
  _end=$(( $(date +%s) + _timeout ))
  while :; do
    if curl -fsS "$_url" 2>/dev/null | grep -q '"status":"UP"'; then
      log "readiness UP at $_url"
      return 0
    fi
    if [ "$(date +%s)" -ge "$_end" ]; then
      warn "no readiness UP at $_url within ${_timeout}s"
      return 1
    fi
    sleep 5
  done
}

# The 'current' symlink points at the last successfully deployed release directory.
current_release_dir() {
  [ -L "$CURRENT_LINK" ] || return 1
  readlink -f "$CURRENT_LINK" 2>/dev/null || readlink "$CURRENT_LINK"
}

# migrations_changed <new-release-dir> <prev-release-dir>
# The Flyway fingerprint (FLYWAY_MAX_VERSION + FLYWAY_MIGRATIONS_SHA256) is recorded in each
# release.env by the deploy job. Returns 0 (true) when the fingerprint differs OR is missing on
# either side (fail safe -> operator recovery), 1 (false) when identical.
migrations_changed() {
  _new="$1/release.env"; _prev="$2/release.env"
  _nmax=$(env_field "$_new" FLYWAY_MAX_VERSION 2>/dev/null || echo "")
  _nsha=$(env_field "$_new" FLYWAY_MIGRATIONS_SHA256 2>/dev/null || echo "")
  _pmax=$(env_field "$_prev" FLYWAY_MAX_VERSION 2>/dev/null || echo "")
  _psha=$(env_field "$_prev" FLYWAY_MIGRATIONS_SHA256 2>/dev/null || echo "")
  if [ -z "$_nsha" ] || [ -z "$_psha" ]; then
    return 0
  fi
  if [ "$_nmax" = "$_pmax" ] && [ "$_nsha" = "$_psha" ]; then
    return 1
  fi
  return 0
}

preflight_checks() {
  _rd="$1"
  require_cmd docker curl awk grep df date
  docker compose version >/dev/null 2>&1 || die "docker compose v2 is not available"
  [ -d "$_rd" ] || die "release directory not found: $_rd"
  [ -f "$SHARED_ENV" ] || die "missing shared secrets env: $SHARED_ENV"
  for _f in docker-compose.yml "$COMPOSE_OVERRIDE" release.env; do
    [ -f "$_rd/$_f" ] || die "release bundle incomplete: missing $_rd/$_f"
  done
  [ -f "$_rd/release-manifest.json" ] || warn "release-manifest.json missing in $_rd"
  compose "$_rd" config -q || die "docker compose config failed for $_rd"

  _avail=$(df -Pm "$OPT_ROOT" | awk 'NR==2 {print $4}')
  [ "${_avail:-0}" -ge "$DISK_MIN_MB" ] \
    || die "insufficient free disk: ${_avail:-0}MB < ${DISK_MIN_MB}MB"

  # Existing dependency health: only if already running (first deploy has none).
  for _svc in postgres redis; do
    _cid=$(service_container "$_rd" "$_svc" || true)
    if [ -n "$_cid" ]; then
      _st=$(container_state "$_cid")
      log "existing $_svc state: $_st"
      [ "$_st" = unhealthy ] && die "existing $_svc is unhealthy; resolve before deploying"
    fi
  done
  log "preflight OK (free disk ${_avail:-?}MB)"
}

# Start or verify PostgreSQL and Redis WITHOUT recreating them during an application release.
start_dependencies() {
  _rd="$1"
  log "starting/verifying postgres and redis (no recreate)"
  compose "$_rd" up -d --no-recreate postgres redis
  wait_container_healthy "$_rd" postgres || die "postgres did not become healthy"
  wait_container_healthy "$_rd" redis || die "redis did not become healthy"
}

# Compressed PostgreSQL backup before any backend update. Retained in the release directory.
create_backup() {
  _rd="$1"
  _bdir="$_rd/backup"
  mkdir -p "$_bdir"
  _cid=$(service_container "$_rd" postgres || true)
  if [ -z "$_cid" ]; then
    log "no running postgres; skipping backup (first deploy)"
    return 0
  fi
  _pguser=$(compose "$_rd" exec -T postgres printenv POSTGRES_USER 2>/dev/null | tr -d '\r' || echo event_capture)
  _pgdb=$(compose "$_rd" exec -T postgres printenv POSTGRES_DB 2>/dev/null | tr -d '\r' || echo event_capture)
  _out="$_bdir/db-$(date -u +%Y%m%dT%H%M%SZ).sql.gz"
  log "creating compressed postgres backup -> $_out"
  compose "$_rd" exec -T postgres pg_dump -U "$_pguser" "$_pgdb" | gzip > "$_out" \
    || die "postgres backup failed"
  log "backup complete ($(du -h "$_out" 2>/dev/null | awk '{print $1}'))"
}

# Pull only the three pinned application images. The smoke rehearsal can skip the pull
# (EVENT_CAPTURE_SKIP_FETCH=1, images pre-built locally) or build them (EVENT_CAPTURE_BUILD_IMAGES=1).
fetch_app_images() {
  _rd="$1"
  if [ "${EVENT_CAPTURE_SKIP_FETCH:-0}" = "1" ]; then
    log "skipping image fetch (smoke: images already present locally)"
  elif [ "${EVENT_CAPTURE_BUILD_IMAGES:-0}" = "1" ]; then
    log "building application images locally (smoke mode)"
    compose "$_rd" build backend-api backend-worker frontend
  else
    log "pulling pinned application images"
    compose "$_rd" pull backend-api backend-worker frontend
  fi
}

# Recreate API, worker and frontend in that order, gating each on readiness.
recreate_app() {
  _rd="$1"
  log "recreating backend-api"
  compose "$_rd" up -d --no-deps backend-api
  wait_container_healthy "$_rd" backend-api || return 1
  log "recreating backend-worker"
  compose "$_rd" up -d --no-deps backend-worker
  wait_container_healthy "$_rd" backend-worker || return 1
  log "recreating frontend"
  compose "$_rd" up -d --no-deps frontend
  return 0
}

# API + worker container health, plus readiness through the frontend proxy on loopback.
health_check() {
  _rd="$1"
  wait_container_healthy "$_rd" backend-api || return 1
  wait_container_healthy "$_rd" backend-worker || return 1
  _port=$(env_field "$_rd/release.env" PUBLIC_PORT 2>/dev/null || echo 8080)
  wait_http_ready "http://127.0.0.1:${_port:-8080}/actuator/health/readiness" || return 1
  return 0
}

# Record the actually running image references/digests and health output in the release dir.
record_deployment() {
  _rd="$1"
  _port=$(env_field "$_rd/release.env" PUBLIC_PORT 2>/dev/null || echo 8080)
  {
    echo "release_tag=$(basename "$_rd")"
    echo "deployed_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    for _svc in backend-api backend-worker frontend; do
      _cid=$(service_container "$_rd" "$_svc" || true)
      if [ -n "$_cid" ]; then
        _ref=$(docker inspect --format '{{.Config.Image}}' "$_cid" 2>/dev/null || echo "")
        _dig=$(docker inspect --format '{{range .RepoDigests}}{{println .}}{{end}}' "$_cid" 2>/dev/null | head -n1)
        echo "$_svc ref=$_ref digest=$_dig"
      fi
    done
  } > "$_rd/deployed-images.txt"
  {
    echo "# docker compose ps"
    compose "$_rd" ps 2>&1 || true
    echo
    echo "# readiness"
    curl -fsS "http://127.0.0.1:${_port:-8080}/actuator/health/readiness" 2>&1 || true
  } > "$_rd/health.txt"
  log "recorded pulled digests -> $_rd/deployed-images.txt and health -> $_rd/health.txt"
}

# Preserve the failed attempt's container logs into the release dir.
capture_failure_logs() {
  _rd="$1"
  mkdir -p "$_rd/logs"
  compose "$_rd" logs --no-color --tail 500 backend-api backend-worker frontend \
    > "$_rd/logs/failed-$(date -u +%Y%m%dT%H%M%SZ).log" 2>&1 || true
}
